use c_enum::c_enum;

c_enum! {
    #[derive(PartialEq, Eq, Clone, Copy)]
    pub enum Opcodes : u8{ 
        Nop = 0x00,
        Pop = 0x01,
        Pop2 = 0x02,
        Pop4 = 0x03,
        Pop8 = 0x04,
        Dup = 0x05,
        Dup2 = 0x06,
        Dup4 = 0x07,
        Dup8 = 0x08,
        Swap = 0x09,
        Swap2 = 0x0A,
        Swap4 = 0x0B,
        Swap8 = 0x0C,
        Br = 0x0D,
        Briz = 0x0E,
        Call = 0x0F,
        Varref = 0x10,
        Iconst = 0x11,
        Iload = 0x12,
        Istore = 0x13,
        Iret = 0x14,
        Inot = 0x15,
        Ior = 0x16,
        Iand = 0x17,
        Ixor = 0x18,
        Ilshr = 0x19,
        Iashr = 0x1A,
        Ishl = 0x1B,
        Ineg = 0x1C,
        Iadd = 0x1D,
        Isub = 0x1E,
        Imul = 0x1F,
        Idiv = 0x20,
        Udiv = 0x21,
        Irem = 0x22,
        Urem = 0x23,
        Ieq = 0x24,
        Ine = 0x25,
        Ige = 0x26,
        Igt = 0x27,
        Uge = 0x28,
        Ugt = 0x29,
        Ilt = 0x2A,
        Ile = 0x2B,
        Ule = 0x2C,
        Ult = 0x2D,
        Iconv = 0x2E,
        Uconv = 0x2F
    }
}

pub mod operand {
    pub type Imm = i64;
    pub type BlkId = u32;
    pub type FnId = u32;
    pub type VarId = u32;
    pub type Isize = u32;
}

#[derive(PartialEq, Eq, Debug, Clone, Copy)]
pub enum Instruction {
    Nop(),
    Pop(),
    Pop2(),
    Pop4(),
    Pop8(),
    Dup(),
    Dup2(),
    Dup4(),
    Dup8(),
    Swap(),
    Swap2(),
    Swap4(),
    Swap8(),
    Br(operand::BlkId),
    Briz(operand::BlkId,operand::BlkId),
    Call(operand::FnId),
    Varref(),
    Iconst(operand::Isize,operand::Imm),
    Iload(operand::Isize),
    Istore(operand::Isize),
    Iret(operand::Isize),
    Inot(operand::Isize),
    Ior(operand::Isize),
    Iand(operand::Isize),
    Ixor(operand::Isize),
    Ilshr(operand::Isize),
    Iashr(operand::Isize),
    Ishl(operand::Isize),
    Ineg(operand::Isize),
    Iadd(operand::Isize),
    Isub(operand::Isize),
    Imul(operand::Isize),
    Idiv(operand::Isize),
    Udiv(operand::Isize),
    Irem(operand::Isize),
    Urem(operand::Isize),
    Ieq(operand::Isize),
    Ine(operand::Isize),
    Ige(operand::Isize),
    Igt(operand::Isize),
    Uge(operand::Isize),
    Ugt(operand::Isize),
    Ilt(operand::Isize),
    Ile(operand::Isize),
    Ule(operand::Isize),
    Ult(operand::Isize),
    Iconv(operand::Isize,operand::Isize),
    Uconv(operand::Isize,operand::Isize),
}

impl Instruction {
    pub fn opcode(&self) -> Opcodes {
        match self {
            Self::Nop(..) => Opcodes::Nop,
            Self::Pop(..) => Opcodes::Pop,
            Self::Pop2(..) => Opcodes::Pop2,
            Self::Pop4(..) => Opcodes::Pop4,
            Self::Pop8(..) => Opcodes::Pop8,
            Self::Dup(..) => Opcodes::Dup,
            Self::Dup2(..) => Opcodes::Dup2,
            Self::Dup4(..) => Opcodes::Dup4,
            Self::Dup8(..) => Opcodes::Dup8,
            Self::Swap(..) => Opcodes::Swap,
            Self::Swap2(..) => Opcodes::Swap2,
            Self::Swap4(..) => Opcodes::Swap4,
            Self::Swap8(..) => Opcodes::Swap8,
            Self::Br(..) => Opcodes::Br,
            Self::Briz(..) => Opcodes::Briz,
            Self::Call(..) => Opcodes::Call,
            Self::Varref(..) => Opcodes::Varref,
            Self::Iconst(..) => Opcodes::Iconst,
            Self::Iload(..) => Opcodes::Iload,
            Self::Istore(..) => Opcodes::Istore,
            Self::Iret(..) => Opcodes::Iret,
            Self::Inot(..) => Opcodes::Inot,
            Self::Ior(..) => Opcodes::Ior,
            Self::Iand(..) => Opcodes::Iand,
            Self::Ixor(..) => Opcodes::Ixor,
            Self::Ilshr(..) => Opcodes::Ilshr,
            Self::Iashr(..) => Opcodes::Iashr,
            Self::Ishl(..) => Opcodes::Ishl,
            Self::Ineg(..) => Opcodes::Ineg,
            Self::Iadd(..) => Opcodes::Iadd,
            Self::Isub(..) => Opcodes::Isub,
            Self::Imul(..) => Opcodes::Imul,
            Self::Idiv(..) => Opcodes::Idiv,
            Self::Udiv(..) => Opcodes::Udiv,
            Self::Irem(..) => Opcodes::Irem,
            Self::Urem(..) => Opcodes::Urem,
            Self::Ieq(..) => Opcodes::Ieq,
            Self::Ine(..) => Opcodes::Ine,
            Self::Ige(..) => Opcodes::Ige,
            Self::Igt(..) => Opcodes::Igt,
            Self::Uge(..) => Opcodes::Uge,
            Self::Ugt(..) => Opcodes::Ugt,
            Self::Ilt(..) => Opcodes::Ilt,
            Self::Ile(..) => Opcodes::Ile,
            Self::Ule(..) => Opcodes::Ule,
            Self::Ult(..) => Opcodes::Ult,
            Self::Iconv(..) => Opcodes::Iconv,
            Self::Uconv(..) => Opcodes::Uconv,
        }
    }
}
