[package]
name = "jolang_runtime"
version.workspace = true
edition = "2021"

[dependencies]
anyhow = "1.0.86"
inkwell = { version = "0.4.0", features = ["llvm17-0"] }
llvm-sys = { version = "170", features = ["prefer-static"] }
